/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formularios;

import SQL.Conection_DB;
import SQL.Metodos_SQL;
import java.awt.Image;
import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.sql.SQLException;

/**
 *
 * @author eswinpineda
 */
public final class Frm_login extends javax.swing.JFrame {

    /**
     * Creates new form Frm_login
     */
    public Frm_login() {
        initComponents();
        setLocationRelativeTo(null);
        iconoFormulario();
        ajustarLogo();
    }
    
    private static Connection conexion;
    private static PreparedStatement sentencia_preparada;
    private static ResultSet resultado;
    
    Metodos_SQL metodos_SQL = new Metodos_SQL();
    Frm_menu_principal frm_menu_principal = new Frm_menu_principal();
    
    public void iconoFormulario()
    {
        URL url = getClass().getResource("/imagenes/Icono_del_sistema.png");
        ImageIcon icono_formulario = new ImageIcon(url);
        setIconImage(icono_formulario.getImage());
    }
    
    public void ajustarLogo()
    {
        ImageIcon logo;
        logo = new ImageIcon(getClass().getResource("/imagenes/logo_java.png"));
        Icon icono_logo = new ImageIcon(logo.getImage().getScaledInstance(lblLogo.getWidth(), lblLogo.getHeight(), Image.SCALE_SMOOTH));
        lblLogo.setIcon(icono_logo);
    }
    
    public void  btnIniciarLblEntrar()
    {
        ImageIcon lblIconoImagen;
        lblIconoImagen = new ImageIcon(getClass().getResource("/imagenes/aceptar.png"));
        Icon icono_lbl = new ImageIcon(lblIconoImagen.getImage().getScaledInstance(
                lblIcono.getWidth(), lblIcono.getHeight(), Image.SCALE_SMOOTH));
        lblIcono.setIcon(icono_lbl);       
    }
    
    public void btnIniciarLblSalir()
    {
        lblIcono.setIcon(null);
    }
    
    public void  btnSalirLblEntrar()
    {
        ImageIcon lblIconoImagen;
        lblIconoImagen = new ImageIcon(getClass().getResource("/imagenes/salir.png"));
        Icon icono_lbl = new ImageIcon(lblIconoImagen.getImage().getScaledInstance(
                lblIcono.getWidth(), lblIcono.getHeight(), Image.SCALE_SMOOTH));
        lblIcono.setIcon(icono_lbl);       
    }
    
    public void btnSalirLblSalir()
    {
        lblIcono.setIcon(null);
    }
    
    public void validarEntrada(String user, String password)
    {
        String mensaje = metodos_SQL.buscarUserLogin(user, password);
        String nombre = null;
        
        if (mensaje.equals("Correcto"))
        {
            try{
                conexion = Conection_DB.conectar();
                String consulta = "SELECT nombre_usuario FROM Usuarios WHERE nombre_usuario = ?";
                sentencia_preparada = conexion.prepareStatement(consulta);
                sentencia_preparada.setString(1, user);
                resultado = sentencia_preparada.executeQuery();
                if(resultado.next()){
                    nombre = resultado.getString("nombre_usuario");
                }
            } catch (SQLException e){
                System.out.println("Error: " + e);
            }
            
            JOptionPane.showMessageDialog(null, "Bienvenido (a)\n" + nombre);
            frm_menu_principal.lblNombreSesion.setText(nombre);
            frm_menu_principal.setVisible(true);
            this.dispose();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Error en el User o Password");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogo = new javax.swing.JLabel();
        btnIniciar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        lblIcono = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Acceso al Sistema");
        setMaximumSize(new java.awt.Dimension(410, 530));
        setMinimumSize(new java.awt.Dimension(410, 530));
        setPreferredSize(new java.awt.Dimension(410, 530));
        getContentPane().setLayout(null);

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo_java.png"))); // NOI18N
        getContentPane().add(lblLogo);
        lblLogo.setBounds(70, 10, 280, 190);

        btnIniciar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnIniciar.setText("Iniciar");
        btnIniciar.setBorder(new javax.swing.border.MatteBorder(null));
        btnIniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnIniciarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnIniciarMouseExited(evt);
            }
        });
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIniciar);
        btnIniciar.setBounds(40, 390, 110, 70);

        btnCancelar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(new javax.swing.border.MatteBorder(null));
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelarMouseExited(evt);
            }
        });
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(170, 390, 110, 70);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 330, 100, 22);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SISTEMA HASH DE ABC");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 230, 280, 22);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("User:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 280, 100, 22);

        txtUser.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(txtUser);
        txtUser.setBounds(180, 273, 170, 30);

        txtPassword.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(txtPassword);
        txtPassword.setBounds(180, 323, 170, 30);
        getContentPane().add(lblIcono);
        lblIcono.setBounds(290, 380, 90, 90);

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo_azul.jpg"))); // NOI18N
        getContentPane().add(lblFondo);
        lblFondo.setBounds(-8, -3, 430, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void btnIniciarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIniciarMouseEntered
        btnIniciarLblEntrar();
    }//GEN-LAST:event_btnIniciarMouseEntered

    private void btnCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseExited
        btnIniciarLblSalir();
    }//GEN-LAST:event_btnCancelarMouseExited

    private void btnIniciarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIniciarMouseExited
        btnIniciarLblSalir();
    }//GEN-LAST:event_btnIniciarMouseExited

    private void btnCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseEntered
        btnSalirLblEntrar();
    }//GEN-LAST:event_btnCancelarMouseEntered

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        validarEntrada(txtUser.getText(), txtPassword.getText());
    }//GEN-LAST:event_btnIniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblIcono;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
